export declare const DefaultPrintCss = "\n\n/**\n * \n * This file hides non-editor content for printing. You should add your own style file\n * rather than edit this one (unless you know what you're doing).\n *\n * **/\n\n@media print {\n  body * {\n    visibility: hidden;\n    overflow: visible !important;\n    -webkit-print-color-adjust: exact !important;\n    pointer-events: none !important;\n  }\n\n  main {\n    top: 0;\n    left: 0;\n    position: absolute;\n    width: 100vw;\n    height: auto;\n  }\n\n  main > div > div:first-child {\n    display: none !important;\n  }\n\n  #editor * {\n    visibility: visible;\n    overflow: visible !important;\n    color: #000 !important;\n  }\n\n  #editor {\n    width: 100vw;\n    height: auto;\n    position: absolute;\n    left: 0;\n    top: 0;\n  }\n\n  #editor:first-child {\n    width: 100vw;\n    height: auto;\n    margin: 0;\n    padding-top: 0;\n    padding-bottom: 0;\n    background-color: white !important;\n  }\n\n  @page {\n    size: auto;\n    margin: 0.5cm;\n  }\n}\n";
export declare const A4PageCss = "\n\n/* mostly required for table */\n:root {\n\t--gray-light-color:rgba(0,0,0,.2);\n  --gray-light2-color:rgba(0,0,0,.1);\n  --divider-color: var(--gray-light-color);\n}\n\n#documenteditor {\n\twidth: 210mm;\n\tbackground:white;\n\tmargin:16px;\n\tcolor: rgba(0,0,0,.9);\n}\n\n";
export declare const DefaultScript = "\n/**\n\nExecute a script against the current editor data model which is passed as context.nodes. \n\n**/\n\n(context) => {\n \n  let nodes = context.nodes;\n\n  console.log(nodes);\n}\n";
export declare const LoadExternalLibScript = "\n\n/**\n\nExample of loading an external library. Only https://unpkg.com is allowed for now in a Chrome extension. \n\n**/\n\n(context) => {\n\n  const generateAPdf = () => {\n\t\tconst doc = new jsPDF()\n\t\tdoc.text('Hello world!', 10, 10)\n\t\tdoc.save('a4.pdf')\n\t} \n\n // Load an array of dependencies. Once completed the callback gets called\n\tcontext\n\t\t.loadJs([\"https://unpkg.com/jspdf@latest/dist/jspdf.min.js\"], generateAPdf);\n\n}\n\n";
export declare const DefaultCssPrintFile: import("./CodeFile").CodeFile;
export declare const DefaultScriptFile: import("./CodeFile").CodeFile;
export declare const A4PageCssFile: import("./CodeFile").CodeFile;
export declare const LoadExternalScriptFile: import("./CodeFile").CodeFile;
export declare const DefaultCodeFiles: import("./CodeFile").CodeFile[];
